### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by Panzerbjrn**
Fixed 'many' to may which contextually seems to be what was meant.

### CODE REVIEW

**Comment by iainbrighton** [comment]
Not sure why the tests are failing? Looks good - Thanks!

**Comment by Panzerbjrn** [comment]
Strange, still showing as an open pull request.

**Comment by iainbrighton** [comment]
@Panzerbjrn I'm trying to get the build server configuration resolved, but I'm not sure what's going on. I'll merge this as it's only fixing a type 😜.

**Comment by Panzerbjrn** [comment]
No worries, cheers...

**Pull request merged**
