### PR TITLE
Fix for #118 - Needs discussing

### PR DESCRIPTION
**Pull request by kilasuit**
@iainbrighton - here is the fix for #118 however there are a few points that need discussed possibly better via skype as this is a big change to the module.

- Tests - I have left them in as they were whilst also adding in my own non-functional tests in as well - check the Private\Tests folder along with the Public\Verb\Tests folders - you'll see what I mean when you have a look at this.

- Build.psake.ps1 - I have left this alone as I have added PesterTest.ps1 & Min.Tests.ps1 for localised testing which works for the requirements found so far (some errors as can be found in the testresults.xml)

### CODE REVIEW

**Comment by iainbrighton** [comment]
Awesome! That's a s*&^ load of functions...

I'm happy to discuss via Skype. My immediate thinking is that this probably wants to go into a separate branch until the tests and build are working... I think I'll need to create a new branch?

**Comment by kilasuit** [comment]
Yes if you could create a new branch "split" that would be great and I'll get working on the failing tests too.

**Comment by iainbrighton** [comment]
@kilasuit Branch `split` should now be available. Can you push to this branch instead? Thanks!

**Comment by kilasuit** [comment]
I'm sure that you can reopen and then change the branch it is going to point to

**Comment by kilasuit** [comment]
Infact I could do it this is now pointing to the split branch 😉

**Pull request merged**
