### PR TITLE
Changed media.json to reflect the current ImageNames in the Server 2016 Eval ISO

### PR DESCRIPTION
**Pull request by svenvanrijen**
Changed media.json to reflect the current ImageNames in the Server 2016 Eval ISO

### CODE REVIEW

**Comment by svenvanrijen** [comment]
Mmm, test failed. But no idea what I can do to fix this...

**Comment by iainbrighton** [comment]
Hi @svenvanrijen. Where did you get these image names? When I download the ISO from the URI in the JSON, I get the following names:

image

If there's a new ISO, we'll need to update the download links too.

**Comment by svenvanrijen** [comment]
Hi @iainbrighton . I got those from the ISO i've downloaded earlier this week (Monday I believe), using the URI that's in the original media.json file (http://download.microsoft.com/download/1/6/F/16FA20E6-4662-482A-920B-1A45CF5AAE3C/14393.0.160715-1616.RS1_RELEASE_SERVER_EVAL_X64FRE_EN-US.ISO)

image

**Comment by svenvanrijen** [comment]
@iainbrighton This is the latest downloadlink from the TechNet site. Will check the Image Names again and change the media.json accordingly.

**Comment by svenvanrijen** [comment]
Hi @iainbrighton 
Image names stay the same, also for the latest version of the ISO.

Cheers!

**Comment by iainbrighton** [comment]
@svenvanrijen I'm not sure what OS/PowerShell/ADK version you're running, but I think I've found out where the discrepancy is coming from:

image

It looks like the output you're getting originates from DISM.EXE output and this varies from the `Get-WindowsImage` cmdlet output. I'll need to do some testing..

**Comment by svenvanrijen** [comment]
Hi @iainbrighton ,

I'm running the scripts from within VSCode. When I don't change the ImageName value, the script will throw the "New-LabImage : Either the Name or Index parameter is required" error.

**Comment by iainbrighton** [comment]
@svenvanrijen - I think this is your problem. Here I have updated the download link, checksum and left the image name as `Windows Server 2016 SERVERSTANDARDCORE` for the 2016 Server Core media. It works:

image

When the image name is changed to `Windows Server 2016 Standard Evaluation` as per your proposal, it returns a value of 0 for the image index (the default [int] value as it can't locate the image):

image

__I think we need to get to the bottom of why your `Get-WindowsImage` cmdlet returns something completely different to the 3 machines I've tested this on.. What OS, PowerShell and ADK versions are you using?__

**Comment by iainbrighton** [comment]
@svenvanrijen Can you confirm what OS version, PowerShell version and ADK version (if applicable) you have installed?

**Comment by svenvanrijen** [comment]
Hi @iainbrighton ,

OS version: Windows 10, build 17017 pre-release 171010-1400.
Powershell:
Name                           Value
----                           -----
PSVersion                      5.1.17017.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17017.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

ADK: 1703 when generating these overviews. 1709 installed in the mean time, not tested yet.

**Comment by iainbrighton** [comment]
Thanks @svenvanrijen - I'll spin up a VM with the 1703 ADK installed and see what happens and let you know.. 😄

**Comment by iainbrighton** [comment]
@svenvanrijen What output does `gcm Get-WindowsImage | fl` give you?

```powershell
PS C:\Users\Administrator> gcm Get-WindowsImage | fl


Name             : Get-WindowsImage
CommandType      : Cmdlet
Definition       :
                   Get-WindowsImage -ImagePath <string> [-LogPath <string>] [-ScratchDirectory <string>] [-LogLevel
                   <LogLevel>] [<CommonParameters>]

                   Get-WindowsImage -ImagePath <string> -Name <string> [-LogPath <string>] [-ScratchDirectory
                   <string>] [-LogLevel <LogLevel>] [<CommonParameters>]

                   Get-WindowsImage -ImagePath <string> -Index <uint32> [-LogPath <string>] [-ScratchDirectory
                   <string>] [-LogLevel <LogLevel>] [<CommonParameters>]

                   Get-WindowsImage -Mounted [-LogPath <string>] [-ScratchDirectory <string>] [-LogLevel <LogLevel>]
                   [<CommonParameters>]

Path             :
AssemblyInfo     :
DLL              : C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Dism\Microsoft.Dism.PowerShell.dll
HelpFile         : Microsoft.Dism.PowerShell.dll-Help.xml
ParameterSets    : {-ImagePath <string> [-LogPath <string>] [-ScratchDirectory <string>] [-LogLevel <LogLevel>]
                   [<CommonParameters>], -ImagePath <string> -Name <string> [-LogPath <string>] [-ScratchDirectory
                   <string>] [-LogLevel <LogLevel>] [<CommonParameters>], -ImagePath <string> -Index <uint32>
                   [-LogPath <string>] [-ScratchDirectory <string>] [-LogLevel <LogLevel>] [<CommonParameters>],
                   -Mounted [-LogPath <string>] [-ScratchDirectory <string>] [-LogLevel <LogLevel>]
                   [<CommonParameters>]}
ImplementingType : Microsoft.Dism.Commands.GetWindowsImageCommand
Verb             : Get
Noun             : WindowsImage
```

I'm guessing you might get something different in the `DLL` property?

**Comment by svenvanrijen** [comment]
@iainbrighton 
Sure:
image

Looks quite the same to me...

**Comment by iainbrighton** [comment]
@svenvanrijen OK - this is a bug in the 17017 preview build. If we change this to the suggested values, it will break __everyone else__!

image

What we can do as a workaround is [specify the image index](https://github.com/VirtualEngine/Lability/blob/dev/Src/Public/New-LabImage.ps1#L113-L127) in the `ImageName` field instead. Whilst not as readable, it will work everywhere. Does this work for you and are you OK to update the PR?

**Comment by svenvanrijen** [comment]
@iainbrighton Works fine to me! Changed the code and tested it: all works fine!

**Comment by iainbrighton** [comment]
@svenvanrijen I think you need to pull in the latest dev branch to get the tests to pass..

**Comment by svenvanrijen** [comment]
@iainbrighton Check. All checks have passed!

**Comment by iainbrighton** [comment]
Thanks for your contribution @svenvanrijen 😃!

**Pull request merged**
