### PR TITLE
Iterate through all switches when running Test-LabVM

### PR DESCRIPTION
**Pull request by absolutejam**
Hey,

I've been having an issue when defining multiple virtual switches in my config file as the switches aren't iterated through, and therefore Test-LabVM is trying to validate against the actual array.

The error I was getting was:
```powershell
Testing Virtual Switch configuration 'System.Object[]'.
Test-LabVM : Cannot process argument transformation on parameter 'Name'. Cannot convert 
value to type System.String.
At C:\Program Files\WindowsPowerShell\Modules\Lability\Src\LabConfiguration.ps1:40 char:32
+ ... onfigured = Test-LabVM -Name $node.NodeName -ConfigurationData $Confi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-LabVM], ParameterBindingArgumentTran 
   sformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Test-LabVM
```

I must admit, I don't really know how to use git in a team environment (I basically only ever push/pull my own stuff), so I apologies if there are conflicts or it doesn't fit the code standards.

If the pull request is garbage, I'd appreciate if somebody could look over what i'm trying to achieve and implement it themself :)

Cheers!

### CODE REVIEW

**Comment by iainbrighton** [comment]
@absolutejam Good catch! Not sure how this hasn't been picked up already?!

Code looks good, but any chance you can add a unit test to catch any future regressions? If you're not up-to-speed with Pester, this would be a gentle introduction 😛

**Comment by absolutejam** [comment]
I haven't forgotten about this, I just need to find time to play! 

I've dabbled before, but this might be the real-world use of Pester I need before it clicks.

**Comment by iainbrighton** [comment]
@absolutejam Yep! You should only need to add one or two tests. Easy right?! 😉

**Comment by iainbrighton** [comment]
@absolutejam Hi James - any update on this PR? Thanks, Iain

**Pull request merged**
