### PR TITLE
Add SupportsShouldProcess support to Remove-LabConfiguration

### PR DESCRIPTION
**Pull request by csandfeld**
Let me know if it meets your standards :)

### CODE REVIEW

**Comment by iainbrighton** [comment]
I'll try and take a look this week. You know, I'll just be busy. Drinking beer ;). It's a shame you can't make it :(

**Comment by csandfeld** [comment]
I'm not at all jealous :)

**Comment by iainbrighton** [comment]
@csandfeld I'm back having spent a few days in conversations, technical sessions and beer drinking (shame you couldn't make it)! I'll get this reviewed this week. I have a bug fix to push which hopefully won't create any merge conflicts for you..

**Comment by iainbrighton** [comment]
@csandfeld Sorry - you now have a merge conflict :(

**Comment by csandfeld** [comment]
No worries :)

**Comment by csandfeld** [comment]
Resolved conflict again the other day, so should be ready for pull. Let me know if anything else needs changing.

**Comment by iainbrighton** [comment]
Right - looks good to me and I think you've got the hang of it!
```powershell
[38] C:\..\Dropbox\PowerShell\> Remove-LabConfiguration -ConfigurationData .\Modules\Lability\Examples\NanoExample.psd1
-WhatIf
What if: Performing the operation "RemoveLabVM" on target "NANO1".
[39] C:\..\Dropbox\PowerShell\> Remove-LabConfiguration -ConfigurationData .\Modules\Lability\Examples\NanoExample.psd1
-Verbose -Confirm
VERBOSE: [12:31:05] Started Lab configuration.

Confirm
Are you sure you want to perform this action?
Performing the operation "RemoveLabVM" on target "NANO1".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
VERBOSE: [12:31:07] Removing VM 'NANO1' snapshot 'Lability Baseline Snapshot'.
VERBOSE: [12:31:07] Removing VM configuration 'NANO1'.
VERBOSE: [12:31:08] Invoking command 'Test-VMTargetResource'.
VERBOSE: [12:31:08] Testing 'Test-VMTargetResource' failed.
VERBOSE: [12:31:08] Invoking command 'Set-VMTargetResource'.
VERBOSE: [12:31:08] Removing VHDX configuration 'NANO1.vhdx'.
VERBOSE: [12:31:08] Invoking command 'Test-VHDTargetResource'.
VERBOSE: [12:31:08] Testing 'Test-VHDTargetResource' failed.
VERBOSE: [12:31:08] Invoking command 'Set-VHDTargetResource'.
VERBOSE: [12:31:08] Finished Lab configuration.
```
I do get prompted for each VM in the configuration, but don't get prompted for each underlying resource e.g. prompted to remove the individual snapshots and disk too. I'm going to merge this one in :+1:

**Comment by csandfeld** [comment]
Cheers 👍

**Pull request merged**
