### PR TITLE
Fixes #55

### LINKED ISSUE #55: Environment variables not expanded when running New-LabVM
On a system with default settings:

```PowerShell
D:\Lability> Get-LabHostDefault


ConfigurationPath       : %SYSTEMDRIVE%\Lability\Configurations
DifferencingVhdPath     : %SYSTEMDRIVE%\Lability\VMVirtualHardDisks
HotfixPath              : %SYSTEMDRIVE%\Lability\Hotfixes
IsoPath                 : %SYSTEMDRIVE%\Lability\ISOs
ParentVhdPath           : %SYSTEMDRIVE%\Lability\MasterVirtualHardDisks
ResourcePath            : %SYSTEMDRIVE%\Lability\Resources
ResourceShareName       : Resources
UpdatePath              : 
DisableLocalFileCaching : False
```

ISO file is downloaded to a path under current directory named "%SYSTEMDRIVE%\Lability\ISOs". Similar issue to the one reported in #33

### PR DESCRIPTION
**Pull request by csandfeld**

### CODE REVIEW

**Comment by csandfeld** [comment]
Hmm ... implemented fix cause tests to fail, and numeric values to be treated as strings. Will have to come up with something better.

**Comment by iainbrighton** [comment]
That change shouldn’t cause the tests to fail. Will take a look as I saw something similar the other day, but that’s related to multiple modules in different $PSModulePath…

**Comment by iainbrighton** [comment]
Looking at the test failures, it looks like a string comparison error, e.g. you’re converting Int values into strings by trying to expand them. You probably only want to try and only expand String value types, not everything?

**Comment by csandfeld** [comment]
I came to the same conclusion. I originaly became aware of the problem because Set-LavVMDefault threw the following error:

```PowerShell
Startup memory '2147483648' cannot be less than minimum memory '536870912'.
At D:\Lability\Src\LabVMDefaults.ps1:179 char:13
+             throw ($localized.StartMemLessThanMinMemError -f $vmDefau ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Startup memory ...ry '536870912'.:String) [], RuntimeException
    + FullyQualifiedErrorId : Startup memory '2147483648' cannot be less than minimum memory '536870912'.
```

Have added a condition to only do expansion for string values, that seems to do the trick.
Will commit and submit PR shortly.

**Pull request closed without merging**
