### PR TITLE
Add Support for VMWare Labs API

### PR DESCRIPTION
**Pull request by barroei**

### CODE REVIEW

**Comment by iainbrighton** [comment]
@barroei Did you mean to submit this PR as there appears to be nothing included?!

**Comment by barroei** [comment]
Yes,  i saw that you have full support for Hyper-V and wanted to ask about
support for VMWare.

**Comment by iainbrighton** [comment]
Ah. Pull requests are used to submit actual code changes. You should raise an issue instead so we can discuss the implementation.

**Comment by kilasuit** [comment]
As this has no code to be added to Lability should this be closed @iainbrighton ?

It can always be opened again in future if needs be.

**Comment by iainbrighton** [comment]
Closing - if there is some discussions required they can take place in the Issues.

**Pull request closed without merging**
